### ISSUE TITLE
Handle Existing "redirect" objects and paths without file extensions or a trailing slash

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist-proxy#113]
## User Story
Handle Existing "redirect" objects and paths without file extensions or a trailing slash

## Background
The garden build currently creates "redirect" objects for every file ending in `index.html` at the raw directory of the file.

Example:
  actual file: `foo/index.html`
  redirect object: `foo`

The result is when `foo` is requested, S3 (and the proxy) returns a 301 to `foo/index.html`.

If an actual file exists at `foo`, no redirect will be created, S3 returns the file and the proxy will serve it with our default content-type of `binary/octet-stream` forcing the browser to handle with a file download.

If not file exists at `foo` or `foo/index.html` and therefore no "redirect" object was created, the proxy returns a 404.

The recently updated logic handles `foo` by first checking S3 and returns the response if it is not an error. In the case where a "redirect" object exists, the new logic just returns it instead of returning with a redirect. To be consistent with the existing behavior, the expected behavior for "redirect" objects (while they exist) should be respected.

Current proxy behavior
| `/foo` is a | production | staging | |
| -- | -- | -- | -- |
| file | **status:** 200</br> **content:** `/foo` content</br> **content-type:** the content type or S3 default | **status:** 200</br> **content:** `/foo` content</br> **content-type:** the content type or S3 default | ✅ |
| "redirect" object | **status:** 200</br> **content:** `/foo/index.html` content</br> **content-type:** `text/html` | **status:** 200</br> **content:** "/foo/index.html"</br> **content-type:** `binary/octet-stream` | ❌ |
| does not exist | **status:** 404</br> **content:** configured 404 page</br> **content-type:** `text/html` | **status:** 301</br> **location:** /foo/</br> **content-type:** `text/html` | ❌ |

## Implementation
Assumes we have access to lua via OpenResty in the nginx buildpack, it's possible this may have to be explicitly configured (https://github.com/cloudfoundry/nginx-buildpack/blob/master/src/nginx/supply/supply.go). Must also use [open resty docker image](https://hub.docker.com/r/openresty/openresty/#!) when testing.

We should be able to replace
```
      location ~ ^([^.\?]*[^/])$ {
        proxy_pass $bucket_url;
        proxy_intercept_errors on;
        error_page 404 403 = @addslash;
      }
```

with something like
```
      location ~ ^([^.\?]*[^/])$ {
          proxy_pass $bucket_url;
          proxy_intercept_errors on;
          error_page 404 403 =404 @notfound;

          header_filter_by_lua_block {
              local redirectlocation = ngx.resp.get_headers()['x-amz-website-redirect-location']
              if type(redirectlocation) == "string" then
                  return ngx.exec(redirectlocation)
              end
          }
      }
```

**Comment by davemcorwin** [comment]
This is...not as simple as I had hoped. In the lua blocks that are run after `proxy_pass` I don't have the ability to perform an internal redirect. So to handle the case of a "redirect object" I can either:
- replace `proxy_pass` and handle all of the logic in lua (make the request to S3 explicitly and handle)
- just return a redirect to the client in this case (I have to confirm this works, but i should be able to set the Location header and perhaps status in `header_filter_by_lua_block`)

**Comment by davemcorwin** [comment]
OK, I have 3 options:
1. For every path `/foo`, try `/foo/index.html`, handle 404/403 by trying `/foo`, handle 404/403 with 404 page

This exhibits the same external behavior but results in an extra trip between the proxy and S3 for every `/foo`, instead of just when there is a "redirect" object. This works bc there will never be files at both `/foo` and `/foo/index.html` since this is originally backed by a file systems and the garden build only generates "redirect" objects for `/foo/index.html`.

I have a working implementation that still leverages `proxy_pass` and require minimal rework.

2. For every path `/foo`, try `/foo`, handle "redirect" object with sending a 302 to client with Location from "redirect" object (`/foo/index.html`).
This exhibits different external behavior and results in an extra round trip from the client to the proxy when there is a "redirect" object.

I have a working implementation that still leverages `proxy_pass` and require rework including lua.

3. For every path `/foo`, handle "redirect" object by trying `/foo/index.html`, exactly as S3 does

I do NOT have a working implementation yet as this requires replacing `proxy_pass` with lua.

My vote is for option 1 as it is the simplest to implement, does not require lua and provides the same external behavior with minimal performance impact.


Thoughts? Questions? Concerns? @18F/federalist-admins

**Comment by svenaas** [comment]
I lean toward option 1 as it doesn't send a 302 to the client. 

Mind you, I think there may be an _SEO_ case to make for 302-ing the client request (if we wanted to canonicalize URLs as /foo/index.html instead of /foo) but if we're going for a general rule here I think having both URLs just work is preferable. Option 3 would achieve the same result for the client, but it's more work and I don't have a reason to think it's worth the effort.

**Comment by davemcorwin** [comment]
yeah, we're not making an SEO judgement here, given how it currently works. I'm pursuing option 1, though of course something about it is not working as expected...

**Comment by davemcorwin** [comment]
Part of #105
