### ISSUE TITLE
CodeQL Reflected XSS

### ISSUE THREAD

**Issue by priceluke** [18F/federalist-proxy#154]
CodeQL flags `mock.js` as having a possible reflected XSS vulnerability. As it is just a mock file, I'm sure it isn't an issue.

![image](https://user-images.githubusercontent.com/44372546/172477831-4c988a45-4217-4c48-bb23-95c2488366d4.png)

**Comment by davemcorwin** [comment]
Thanks @priceluke . Yep, this is just used when testing locally or CI, so not an issue.
