### ISSUE TITLE
Resolve redirects issue noted in H1

### ISSUE THREAD

**Issue by wslack** [18F/federalist-proxy#17]
Per https://gsa-tts.slack.com/archives/C1NUUGTT5/p1504031973000278

**Comment by jseppi** [comment]
As discussed in slack, I'm pretty sure this is an issue with the cloud.gov router, not with our proxy.

**Comment by wslack** [comment]
@rogerruiz - can you take?

**Comment by wslack** [comment]
Closed as not something Federalist can fix (also not a bug)
