### ISSUE TITLE
X-Frame-Options header not working as intended

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-proxy#26]
ref https://github.com/uswds/uswds/issues/2335

We want to serve `X-Frame-Options: SAMEORIGIN`, as specified in our nginx conf (https://github.com/18F/federalist-proxy/blob/staging/nginx.conf#L43).

After adding CORS support in #24, the `X-Frame-Options` appears to have stopped working for the USWDS. For example, at this URL https://components.designsystem.digital.gov/components/preview/labels--default.html we see `x-frame-options: DENY`when visited in Chrome:

<img width="753" alt="screen shot 2018-02-09 at 8 30 13 am" src="https://user-images.githubusercontent.com/697848/36032399-812e200c-0d73-11e8-9981-d036a9378d6d.png">

Oddly, when requesting headers for that page using `curl`, the `X-Frame-Options` header is properly returned as `SAMEORIGIN`:

<img width="656" alt="screen shot 2018-02-09 at 8 32 04 am" src="https://user-images.githubusercontent.com/697848/36032462-b943b984-0d73-11e8-9035-65878da19aa3.png">

The problem appears to be some weird interaction with:
1) Request from actual browser vs curl
1) The cloud.gov proxy, which by default returns `DENY` for `X-Frame-Options`
1) Usage of [`add_header`](http://nginx.org/en/docs/http/ngx_http_headers_module.html) and [`if`](https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/) statements in our nginx config.

At this point, I do not have an nginx-based solution because I don't fully understand what the bad interaction is.

edit: Removed the notes/observations about header capitalization. That seems to be a red herring because Chrome reports all header names as lowercase.

**Comment by wslack** [comment]
I'm 👍 for this as long as we aren't leaving technical debt in the NGINX config. Think its worth asking someone else to take a peek (or to query the cloud.gov folks for their opinion on if the current set up is 👎 )?

**Comment by jseppi** [comment]
cloud.gov folks are the ones who suggested reverting the CORS stuff (ie, removing the `if` statements and pointing out the weird `add_header` behavior).

**Comment by jseppi** [comment]
I had multiple people review #24 before merging it, but this interaction seems to be so bizarre that nobody foresaw a problem. At this point, I think the proposed solution above will reduce technical debt.

Unfortunately, as @konklone had previously mentioned, this might create additional burden or a different solution if/when we want to handle CORS on a site-by-site basis.

**Comment by wslack** [comment]
👍

**Comment by jseppi** [comment]
`federalist-staging`'s Bucket CORS policy has been updated and the staging `proxy` has been deployed after #27. Everything looks good there to me:

<img width="805" alt="screen shot 2018-02-09 at 11 28 51 am" src="https://user-images.githubusercontent.com/697848/36040926-9a5f3aa2-0d8c-11e8-81c7-05bd92b5d1da.png">

Note the `Access-Control-*` headers working for the `https://s.codepen.io` `Origin`.

**Comment by jseppi** [comment]
Here's a pen for testing: https://codepen.io/anon/pen/mXrXVR?editors=1111 (expand the Console section to see results).

**Comment by jseppi** [comment]
Alright, `federalist-registry` has been deployed to `production` and the CORS policy has been set on the production s3 bucket.

**Comment by jseppi** [comment]
Looks fixed to me!

<img width="767" alt="screen shot 2018-02-09 at 1 20 00 pm" src="https://user-images.githubusercontent.com/697848/36045642-fbeb6458-0d9b-11e8-8d80-7d3cce7f28cb.png">

**Comment by wslack** [comment]
And confirmed by Maya!
