### ISSUE TITLE
Migrate to nginx-buildpack

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-proxy#31]
### User Story
As a user of Federalist, I want to ensure that the proxy that transmits information for all of my sites is secure and remains up permanently.

### Background
This app currently uses the staticfiles-buildpack, but overrides the nginx.conf to meet the needs of our reverse proxy. Overriding the nginx.conf in the staticfiles-buildpack is now deprected by Cloud Foundry, and instead the `nginx-buildpack` should be used.

deprecation info: https://www.pivotaltracker.com/n/projects/1042066/stories/150296977

buildpack docs link: https://github.com/cloudfoundry/nginx-buildpack

If we don't replace this, eventually the the current publishing mechanism will no longer be supported and the proxy will fail irrevocably.

### Acceptance Criteria
- [x] A user can view their federalist built site using their custom domain (ie: https://federalist-docs.18f.gov/) and see all content and images rendered

After evaluating, edit this part:

Level of effort - low

Implementation outline:
- [x] update manifest to use nginx-buildpack

**Comment by wslack** [comment]
@amirbey I feel like this might be a great issue to tackle or look at as you ramp up; what do you think?

**Comment by amirbey** [comment]
nginx-buildpack is still intended for experimental use and not in production

https://github.com/cloudfoundry/nginx-buildpack

**Comment by amirbey** [comment]
User Story
A user should view their website and assets at custom domain using nginx-buildpack

Acceptance Criteria
- [ ] A user can view their federalist built site using their custom domain (ie: https://federalist-docs.18f.gov/) and see all content and images  rendered

After evaluating, edit this part:

Level of effort - low

Implementation outline:
update manifest to use nginx-buildpack
