### ISSUE TITLE
Evaluate and add `gzip_vary on;` to nginx.conf if necessary

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-proxy#32]
#### User Story

As a user browsing a federslist site, I would like my browser to gzip compress text files if my browser accepts gzip compression

#### Background (Optional)

As a potential short term fix to an issue with overriding nginx.conf in the staticfiles-buildpack (which is now deprected, per #31), we might need to add `gzip_vary on;` to our nginx.conf to maintain previous behavior.

#### Acceptance Criteria

- [x] Enable gzip_vary compression in nginx.conf
- [x] Change made live via by deploying federalist-proxy on staging
- [x] Change made live via by deploying federalist-proxy on production

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by jseppi** [comment]
Even if the deprecation of staticfiles-buildpack does not impact this, it is still probably not a bad idea to include `gzip_vary on`; in our config. Some more info: https://blog.stackpath.com/accept-encoding-vary-important

**Comment by amirbey** [comment]
#### User Story

As a user browsing a federslist site, I would like my browser to gzip compress text files if my browser accepts gzip compression

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] Enable gzip compression in nginx.conf
- [ ] Change made live via by deploying federalist-proxy on staging
- [ ] Change made live via by deploying federalist-proxy on production

_After evaluating, edit this part:_

#### Level of effort - Low

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>
