### ISSUE TITLE
Restore testing locally and in CI

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist-proxy#53]
While there are a handful of tests they are not run in CI and running the app and tests locally is difficult.

Previously CF Local was used to run locally, however, this seems to be unmaintained and does not support the current cflinux stack preferred by Cloud.gov.

1. Update CI and local environment to make running tests simpler
2. Add any missing tests

**Comment by amirbey** [comment]
next steps .... investigate using cf dev
